// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcNK3w0vJDE1hcbwtaClI50zeTI-bw99I',
    appId: '1:951528668411:web:6c19f0b04612149d62845e',
    messagingSenderId: '371301374064',
    projectId: 'lost-pet-dcffd',
    authDomain: 'entelect-app.firebaseapp.com',
    storageBucket: 'entelect-app.appspot.com',
    measurementId: 'G-8TP2LEBKQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCToWxGQZwwyBQa9z_yAAFB1w7ZwdmHZL8',
    appId: '1:371301374064:android:25e4fd51971d7b8c50bcb5',
    messagingSenderId: '371301374064',
    projectId: 'lost-pet-dcffd',
    storageBucket: 'entelect-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz08mfbbNRrDSPz3atNZItFBn9WIkFvYk',
    appId: '1:371301374064:ios:83204293df49926050bcb5',
    messagingSenderId: '371301374064',
    projectId: 'lost-pet-dcffd',
    storageBucket: 'entelect-app.appspot.com',
    iosClientId:
        '951528668411-jiqha4qur2pqq5qhbjvrcihkd2t7ccfu.apps.googleusercontent.com',
    iosBundleId: 'com.entelect.entelectApp',
  );
}
