// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBeb6Z63gIM5wqcZruRzQoPDxgYaowj74',
    appId: '1:371301374064:web:ec5e23d31fbbf05e50bcb5',
    messagingSenderId: '371301374064',
    projectId: 'lost-pet-dcffd',
    authDomain: 'lost-pet-dcffd.firebaseapp.com',
    storageBucket: 'lost-pet-dcffd.appspot.com',
    measurementId: 'G-0LBJW17D83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1rKZLx8TLh3XkPTxRQmR8SJzjhaQBN4A',
    appId: '1:371301374064:android:a9494c5b8d11ca8450bcb5',
    messagingSenderId: '371301374064',
    projectId: 'lost-pet-dcffd',
    storageBucket: 'lost-pet-dcffd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjU4A41FQ2Tq7Qo6Jk-bl6Q8jASpi0F0g',
    appId: '1:371301374064:ios:da82bbcc3386a47f50bcb5',
    messagingSenderId: '371301374064',
    projectId: 'lost-pet-dcffd',
    storageBucket: 'lost-pet-dcffd.appspot.com',
    iosClientId:
        '371301374064-6dleg8og58cpft9gcfu2khrogdueqfvm.apps.googleusercontent.com',
    iosBundleId: 'com.vanzylarno.lostPet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjU4A41FQ2Tq7Qo6Jk-bl6Q8jASpi0F0g',
    appId: '1:371301374064:ios:da82bbcc3386a47f50bcb5',
    messagingSenderId: '371301374064',
    projectId: 'lost-pet-dcffd',
    storageBucket: 'lost-pet-dcffd.appspot.com',
    iosClientId:
        '371301374064-6dleg8og58cpft9gcfu2khrogdueqfvm.apps.googleusercontent.com',
    iosBundleId: 'com.vanzylarno.lostPet',
  );
}
